name: Docker PostGIS CI

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [12, 13, 14, 15, 16]
        postgis: ['3.4']
        variant: [default, alpine]
        include:
          - postgres: 15
            postgis: master
            variant: default
          - postgres: 16
            postgis: master
            variant: default

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push docker image for ${{ env.VERSION }} ${{ env.VARIANT }} to dockerhub
      uses: docker/build-push-action@v4
      env:
        DOCKERFILE_PATH: ${{ matrix.variant == 'default' && 'Dockerfile' || format('{0}/Dockerfile', matrix.variant) }}
        DOCKER_BASE_IMAGE: ${{ matrix.variant == 'default' && '' || format('-{0}', matrix.variant) }}
      with:
        context: .
        file: ./${{ env.VERSION }}/${{ env.DOCKERFILE_PATH }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/postgis:${{ env.VERSION }}${{ env.DOCKER_BASE_IMAGE }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/postgis:cache-${{ env.VERSION }}${{ env.DOCKER_BASE_IMAGE }}
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/postgis:cache-${{ env.VERSION }}${{ env.DOCKER_BASE_IMAGE }},mode=max

